package com.liu.gymmanagement.mapper;

import com.liu.gymmanagement.model.Accesslogs;
import com.liu.gymmanagement.model.AccesslogsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AccesslogsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accesslogs
     *
     * @mbg.generated Tue Apr 08 23:14:53 CST 2025
     */
    long countByExample(AccesslogsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accesslogs
     *
     * @mbg.generated Tue Apr 08 23:14:53 CST 2025
     */
    int deleteByExample(AccesslogsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accesslogs
     *
     * @mbg.generated Tue Apr 08 23:14:53 CST 2025
     */
    int deleteByPrimaryKey(Integer logid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accesslogs
     *
     * @mbg.generated Tue Apr 08 23:14:53 CST 2025
     */
    int insert(Accesslogs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accesslogs
     *
     * @mbg.generated Tue Apr 08 23:14:53 CST 2025
     */
    int insertSelective(Accesslogs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accesslogs
     *
     * @mbg.generated Tue Apr 08 23:14:53 CST 2025
     */
    List<Accesslogs> selectByExample(AccesslogsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accesslogs
     *
     * @mbg.generated Tue Apr 08 23:14:53 CST 2025
     */
    Accesslogs selectByPrimaryKey(Integer logid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accesslogs
     *
     * @mbg.generated Tue Apr 08 23:14:53 CST 2025
     */
    int updateByExampleSelective(@Param("record") Accesslogs record, @Param("example") AccesslogsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accesslogs
     *
     * @mbg.generated Tue Apr 08 23:14:53 CST 2025
     */
    int updateByExample(@Param("record") Accesslogs record, @Param("example") AccesslogsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accesslogs
     *
     * @mbg.generated Tue Apr 08 23:14:53 CST 2025
     */
    int updateByPrimaryKeySelective(Accesslogs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accesslogs
     *
     * @mbg.generated Tue Apr 08 23:14:53 CST 2025
     */
    int updateByPrimaryKey(Accesslogs record);
}