package com.liu.gymmanagement.mapper;

import com.liu.gymmanagement.dto.CapacityLogDTO;
import com.liu.gymmanagement.model.CapacityLog;
import com.liu.gymmanagement.model.CapacityLogExample;
import java.util.List;

import org.apache.ibatis.annotations.*;

@Mapper
public interface CapacityLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table capacity_logs
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    long countByExample(CapacityLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table capacity_logs
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    int deleteByExample(CapacityLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table capacity_logs
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    int deleteByPrimaryKey(Integer logid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table capacity_logs
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    int insert(CapacityLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table capacity_logs
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    int insertSelective(CapacityLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table capacity_logs
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    List<CapacityLog> selectByExample(CapacityLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table capacity_logs
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    CapacityLog selectByPrimaryKey(Integer logid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table capacity_logs
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    int updateByExampleSelective(@Param("record") CapacityLog record, @Param("example") CapacityLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table capacity_logs
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    int updateByExample(@Param("record") CapacityLog record, @Param("example") CapacityLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table capacity_logs
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    int updateByPrimaryKeySelective(CapacityLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table capacity_logs
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    int updateByPrimaryKey(CapacityLog record);

    // 增加当前健身房容量
    @Update("UPDATE capacity_logs SET current_count = current_count + 1 WHERE GymID = #{gymId}")
    @Results({
            @Result(property = "gymid", column = "GymID"),       // 映射 gym_id 到 gymId
            @Result(property = "currentCount", column = "current_count") // 映射 current_count 到 currentCount
    })
    void incrementCurrentCount(@Param("gymId") int gymId);

    // 减少当前健身房容量
    @Update("UPDATE capacity_logs SET current_count = current_count - 1 WHERE GymID = #{gymId} AND current_count > 0")
    @Results({
            @Result(property = "gymid", column = "GymID"),       // 映射 gym_id 到 gymId
            @Result(property = "currentCount", column = "current_count") // 映射 current_count 到 currentCount
    })
    void decrementCurrentCount(@Param("gymId") int gymId);

    @Update("UPDATE capacity_logs SET current_count = 0")
    @Results({
            @Result(property = "currentCount", column = "current_count") // 映射 current_count 到 currentCount
    })
    void resetCurrentCount();

    // 查询所有健身房的当前容量
    @Select("SELECT GymID, current_count FROM capacity_logs")
    @Results({
            @Result(property = "gymid", column = "GymID"),       // 映射 gym_id 到 gymId
            @Result(property = "currentCount", column = "current_count") // 映射 current_count 到 currentCount
    })
    List<CapacityLog> getAllGymCurrentCapacity();

//    @Select("SELECT c.GymID, c.current_count, g.Name " +
//            "FROM capacity_logs c " +
//            "JOIN gym g ON c.GymID = g.GymID")
//    @Results({
//            @Result(property = "gymid", column = "GymID"),
//            @Result(property = "currentCount", column = "current_count"),
//            @Result(property = "name", column = "Name")
//    })
//    List<CapacityLog> getAllGymCurrentCapacityWithNames();

    @Select("SELECT c.GymID, c.current_count, g.Name " +
            "FROM capacity_logs c " +
            "JOIN gym g ON c.GymID = g.GymID")
    @Results({
            @Result(property = "gymId", column = "GymID"),
            @Result(property = "currentCount", column = "current_count"),
            @Result(property = "name", column = "Name")
    })
    List<CapacityLogDTO> getAllGymCurrentCapacityWithNames();
}