package com.liu.gymmanagement.mapper;

import com.liu.gymmanagement.model.CapacityLog;
import com.liu.gymmanagement.model.CapacityLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CapacityLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table capacity_logs
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    long countByExample(CapacityLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table capacity_logs
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    int deleteByExample(CapacityLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table capacity_logs
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    int deleteByPrimaryKey(Integer logid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table capacity_logs
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    int insert(CapacityLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table capacity_logs
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    int insertSelective(CapacityLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table capacity_logs
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    List<CapacityLog> selectByExample(CapacityLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table capacity_logs
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    CapacityLog selectByPrimaryKey(Integer logid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table capacity_logs
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    int updateByExampleSelective(@Param("record") CapacityLog record, @Param("example") CapacityLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table capacity_logs
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    int updateByExample(@Param("record") CapacityLog record, @Param("example") CapacityLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table capacity_logs
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    int updateByPrimaryKeySelective(CapacityLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table capacity_logs
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    int updateByPrimaryKey(CapacityLog record);
}