package com.liu.gymmanagement.mapper;

import com.liu.gymmanagement.model.CapacityConfig;
import com.liu.gymmanagement.model.CapacityConfigExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Update;


public interface CapacityConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table capacity_config
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    long countByExample(CapacityConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table capacity_config
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    int deleteByExample(CapacityConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table capacity_config
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    int deleteByPrimaryKey(Integer configId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table capacity_config
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    int insert(CapacityConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table capacity_config
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    int insertSelective(CapacityConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table capacity_config
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    List<CapacityConfig> selectByExample(CapacityConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table capacity_config
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    CapacityConfig selectByPrimaryKey(Integer configId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table capacity_config
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    int updateByExampleSelective(@Param("record") CapacityConfig record, @Param("example") CapacityConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table capacity_config
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    int updateByExample(@Param("record") CapacityConfig record, @Param("example") CapacityConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table capacity_config
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    int updateByPrimaryKeySelective(CapacityConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table capacity_config
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    int updateByPrimaryKey(CapacityConfig record);


}