package com.liu.gymmanagement.mapper;

import com.liu.gymmanagement.model.Equipment;
import com.liu.gymmanagement.model.EquipmentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EquipmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment
     *
     * @mbg.generated Sat Apr 12 18:44:23 CST 2025
     */
    long countByExample(EquipmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment
     *
     * @mbg.generated Sat Apr 12 18:44:23 CST 2025
     */
    int deleteByExample(EquipmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment
     *
     * @mbg.generated Sat Apr 12 18:44:23 CST 2025
     */
    int deleteByPrimaryKey(Integer equipmentid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment
     *
     * @mbg.generated Sat Apr 12 18:44:23 CST 2025
     */
    int insert(Equipment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment
     *
     * @mbg.generated Sat Apr 12 18:44:23 CST 2025
     */
    int insertSelective(Equipment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment
     *
     * @mbg.generated Sat Apr 12 18:44:23 CST 2025
     */
    List<Equipment> selectByExampleWithBLOBs(EquipmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment
     *
     * @mbg.generated Sat Apr 12 18:44:23 CST 2025
     */
    List<Equipment> selectByExample(EquipmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment
     *
     * @mbg.generated Sat Apr 12 18:44:23 CST 2025
     */
    Equipment selectByPrimaryKey(Integer equipmentid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment
     *
     * @mbg.generated Sat Apr 12 18:44:23 CST 2025
     */
    int updateByExampleSelective(@Param("record") Equipment record, @Param("example") EquipmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment
     *
     * @mbg.generated Sat Apr 12 18:44:23 CST 2025
     */
    int updateByExampleWithBLOBs(@Param("record") Equipment record, @Param("example") EquipmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment
     *
     * @mbg.generated Sat Apr 12 18:44:23 CST 2025
     */
    int updateByExample(@Param("record") Equipment record, @Param("example") EquipmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment
     *
     * @mbg.generated Sat Apr 12 18:44:23 CST 2025
     */
    int updateByPrimaryKeySelective(Equipment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment
     *
     * @mbg.generated Sat Apr 12 18:44:23 CST 2025
     */
    int updateByPrimaryKeyWithBLOBs(Equipment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment
     *
     * @mbg.generated Sat Apr 12 18:44:23 CST 2025
     */
    int updateByPrimaryKey(Equipment record);
}