package com.liu.gymmanagement.mapper;

import com.liu.gymmanagement.model.Feedback;
import com.liu.gymmanagement.model.FeedbackExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FeedbackMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feedbacks
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    long countByExample(FeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feedbacks
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    int deleteByExample(FeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feedbacks
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    int deleteByPrimaryKey(Integer feedbackid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feedbacks
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    int insert(Feedback record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feedbacks
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    int insertSelective(Feedback record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feedbacks
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    List<Feedback> selectByExampleWithBLOBs(FeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feedbacks
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    List<Feedback> selectByExample(FeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feedbacks
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    Feedback selectByPrimaryKey(Integer feedbackid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feedbacks
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    int updateByExampleSelective(@Param("record") Feedback record, @Param("example") FeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feedbacks
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    int updateByExampleWithBLOBs(@Param("record") Feedback record, @Param("example") FeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feedbacks
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    int updateByExample(@Param("record") Feedback record, @Param("example") FeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feedbacks
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    int updateByPrimaryKeySelective(Feedback record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feedbacks
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    int updateByPrimaryKeyWithBLOBs(Feedback record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feedbacks
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    int updateByPrimaryKey(Feedback record);
}