package com.liu.gymmanagement.mapper;

import com.liu.gymmanagement.model.Gym;
import com.liu.gymmanagement.model.GymExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface GymMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gym
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    long countByExample(GymExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gym
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    int deleteByExample(GymExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gym
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    int deleteByPrimaryKey(Integer gymid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gym
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    int insert(Gym record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gym
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    int insertSelective(Gym record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gym
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    List<Gym> selectByExampleWithBLOBs(GymExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gym
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    List<Gym> selectByExample(GymExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gym
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    Gym selectByPrimaryKey(Integer gymid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gym
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    int updateByExampleSelective(@Param("record") Gym record, @Param("example") GymExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gym
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    int updateByExampleWithBLOBs(@Param("record") Gym record, @Param("example") GymExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gym
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    int updateByExample(@Param("record") Gym record, @Param("example") GymExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gym
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    int updateByPrimaryKeySelective(Gym record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gym
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    int updateByPrimaryKeyWithBLOBs(Gym record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gym
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    int updateByPrimaryKey(Gym record);

    //List<Gym> selectAll();

    List<Gym> selectAll();
}