package com.liu.gymmanagement.mapper;

import com.liu.gymmanagement.model.GymTimeslot;
import com.liu.gymmanagement.model.GymTimeslotExample;

import java.time.LocalDate;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

public interface GymTimeslotMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gym_timeslot
     *
     * @mbg.generated Thu Mar 20 22:59:52 CST 2025
     */
    long countByExample(GymTimeslotExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gym_timeslot
     *
     * @mbg.generated Thu Mar 20 22:59:52 CST 2025
     */
    int deleteByExample(GymTimeslotExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gym_timeslot
     *
     * @mbg.generated Thu Mar 20 22:59:52 CST 2025
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gym_timeslot
     *
     * @mbg.generated Thu Mar 20 22:59:52 CST 2025
     */
    int insert(GymTimeslot record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gym_timeslot
     *
     * @mbg.generated Thu Mar 20 22:59:52 CST 2025
     */
    int insertSelective(GymTimeslot record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gym_timeslot
     *
     * @mbg.generated Thu Mar 20 22:59:52 CST 2025
     */
    List<GymTimeslot> selectByExample(GymTimeslotExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gym_timeslot
     *
     * @mbg.generated Thu Mar 20 22:59:52 CST 2025
     */
    GymTimeslot selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gym_timeslot
     *
     * @mbg.generated Thu Mar 20 22:59:52 CST 2025
     */
    int updateByExampleSelective(@Param("record") GymTimeslot record, @Param("example") GymTimeslotExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gym_timeslot
     *
     * @mbg.generated Thu Mar 20 22:59:52 CST 2025
     */
    int updateByExample(@Param("record") GymTimeslot record, @Param("example") GymTimeslotExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gym_timeslot
     *
     * @mbg.generated Thu Mar 20 22:59:52 CST 2025
     */
    int updateByPrimaryKeySelective(GymTimeslot record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gym_timeslot
     *
     * @mbg.generated Thu Mar 20 22:59:52 CST 2025
     */
    int updateByPrimaryKey(GymTimeslot record);

    GymTimeslot selectByExample(int timeslotId);

    List<GymTimeslot> selectFutureTimeslots(@Param("startDate") LocalDate startDate, @Param("endDate") LocalDate endDate);

}