package com.liu.gymmanagement.mapper;

import com.liu.gymmanagement.model.GymTimeslotTemplate;
import com.liu.gymmanagement.model.GymTimeslotTemplateExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GymTimeslotTemplateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gym_timeslot_template
     *
     * @mbg.generated Fri Mar 21 03:45:11 CST 2025
     */
    long countByExample(GymTimeslotTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gym_timeslot_template
     *
     * @mbg.generated Fri Mar 21 03:45:11 CST 2025
     */
    int deleteByExample(GymTimeslotTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gym_timeslot_template
     *
     * @mbg.generated Fri Mar 21 03:45:11 CST 2025
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gym_timeslot_template
     *
     * @mbg.generated Fri Mar 21 03:45:11 CST 2025
     */
    int insert(GymTimeslotTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gym_timeslot_template
     *
     * @mbg.generated Fri Mar 21 03:45:11 CST 2025
     */
    int insertSelective(GymTimeslotTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gym_timeslot_template
     *
     * @mbg.generated Fri Mar 21 03:45:11 CST 2025
     */
    List<GymTimeslotTemplate> selectByExample(GymTimeslotTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gym_timeslot_template
     *
     * @mbg.generated Fri Mar 21 03:45:11 CST 2025
     */
    GymTimeslotTemplate selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gym_timeslot_template
     *
     * @mbg.generated Fri Mar 21 03:45:11 CST 2025
     */
    int updateByExampleSelective(@Param("record") GymTimeslotTemplate record, @Param("example") GymTimeslotTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gym_timeslot_template
     *
     * @mbg.generated Fri Mar 21 03:45:11 CST 2025
     */
    int updateByExample(@Param("record") GymTimeslotTemplate record, @Param("example") GymTimeslotTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gym_timeslot_template
     *
     * @mbg.generated Fri Mar 21 03:45:11 CST 2025
     */
    int updateByPrimaryKeySelective(GymTimeslotTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gym_timeslot_template
     *
     * @mbg.generated Fri Mar 21 03:45:11 CST 2025
     */
    int updateByPrimaryKey(GymTimeslotTemplate record);

    List<GymTimeslotTemplate> selectAll();
}