package com.liu.gymmanagement.mapper;

import com.liu.gymmanagement.model.Report;
import com.liu.gymmanagement.model.ReportExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ReportMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reports
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    long countByExample(ReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reports
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    int deleteByExample(ReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reports
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    int deleteByPrimaryKey(Integer reportid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reports
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    int insert(Report record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reports
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    int insertSelective(Report record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reports
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    List<Report> selectByExampleWithBLOBs(ReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reports
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    List<Report> selectByExample(ReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reports
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    Report selectByPrimaryKey(Integer reportid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reports
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    int updateByExampleSelective(@Param("record") Report record, @Param("example") ReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reports
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    int updateByExampleWithBLOBs(@Param("record") Report record, @Param("example") ReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reports
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    int updateByExample(@Param("record") Report record, @Param("example") ReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reports
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    int updateByPrimaryKeySelective(Report record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reports
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    int updateByPrimaryKeyWithBLOBs(Report record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reports
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    int updateByPrimaryKey(Report record);
}