package com.liu.gymmanagement.mapper;

import com.liu.gymmanagement.model.Reservation;
import com.liu.gymmanagement.model.ReservationExample;
import java.util.List;
import java.util.Optional;

import org.apache.ibatis.annotations.*;

@Mapper
public interface ReservationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reservations
     *
     * @mbg.generated Wed Mar 26 00:44:02 CST 2025
     */
    long countByExample(ReservationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reservations
     *
     * @mbg.generated Wed Mar 26 00:44:02 CST 2025
     */
    int deleteByExample(ReservationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reservations
     *
     * @mbg.generated Wed Mar 26 00:44:02 CST 2025
     */
    int deleteByPrimaryKey(Integer reservationid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reservations
     *
     * @mbg.generated Wed Mar 26 00:44:02 CST 2025
     */
    //@Options(useGeneratedKeys = true, keyProperty = "reservationid", keyColumn = "ReservationID")
    @Insert("INSERT INTO reservations (UserID, GymID, TimeslotID, reservation_time, status, entry_qr_code, exit_qr_code, qr_expiry_time) " +
            "VALUES (#{userid}, #{gymid}, #{timeslotid}, #{reservationTime}, #{status}, #{entryQrCode}, #{exitQrCode}, #{qrExpiryTime})")
    @Options(useGeneratedKeys = true, keyProperty = "reservationid", keyColumn = "ReservationID")
    int insertReservation(Reservation reservation);

    int insert(Reservation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reservations
     *
     * @mbg.generated Wed Mar 26 00:44:02 CST 2025
     */
    int insertSelective(Reservation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reservations
     *
     * @mbg.generated Wed Mar 26 00:44:02 CST 2025
     */
    List<Reservation> selectByExample(ReservationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reservations
     *
     * @mbg.generated Wed Mar 26 00:44:02 CST 2025
     */
    Reservation selectByPrimaryKey(Integer reservationid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reservations
     *
     * @mbg.generated Wed Mar 26 00:44:02 CST 2025
     */
    int updateByExampleSelective(@Param("record") Reservation record, @Param("example") ReservationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reservations
     *
     * @mbg.generated Wed Mar 26 00:44:02 CST 2025
     */
    int updateByExample(@Param("record") Reservation record, @Param("example") ReservationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reservations
     *
     * @mbg.generated Wed Mar 26 00:44:02 CST 2025
     */
    int updateByPrimaryKeySelective(Reservation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reservations
     *
     * @mbg.generated Wed Mar 26 00:44:02 CST 2025
     */
    int updateByPrimaryKey(Reservation record);

    // 查询二维码对应的预订记录
    @Select("SELECT * FROM reservations WHERE entry_qr_code = #{qrCodeData} OR exit_qr_code = #{qrCodeData} LIMIT 1")
    Optional<Reservation> findByEntryQrCodeOrExitQrCode(String qrCodeData);
}