package com.liu.gymmanagement.mapper;

import com.liu.gymmanagement.model.Reservation;
import com.liu.gymmanagement.model.ReservationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ReservationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reservations
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    long countByExample(ReservationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reservations
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    int deleteByExample(ReservationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reservations
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    int deleteByPrimaryKey(Integer reservationid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reservations
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    int insert(Reservation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reservations
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    int insertSelective(Reservation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reservations
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    List<Reservation> selectByExample(ReservationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reservations
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    Reservation selectByPrimaryKey(Integer reservationid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reservations
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    int updateByExampleSelective(@Param("record") Reservation record, @Param("example") ReservationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reservations
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    int updateByExample(@Param("record") Reservation record, @Param("example") ReservationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reservations
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    int updateByPrimaryKeySelective(Reservation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reservations
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    int updateByPrimaryKey(Reservation record);
}