package com.liu.gymmanagement.mapper;

import com.liu.gymmanagement.model.WorkoutLog;
import com.liu.gymmanagement.model.WorkoutLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WorkoutLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workout_log
     *
     * @mbg.generated Sun Apr 13 21:46:58 CST 2025
     */
    long countByExample(WorkoutLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workout_log
     *
     * @mbg.generated Sun Apr 13 21:46:58 CST 2025
     */
    int deleteByExample(WorkoutLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workout_log
     *
     * @mbg.generated Sun Apr 13 21:46:58 CST 2025
     */
    int deleteByPrimaryKey(Integer workoutlogid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workout_log
     *
     * @mbg.generated Sun Apr 13 21:46:58 CST 2025
     */
    int insert(WorkoutLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workout_log
     *
     * @mbg.generated Sun Apr 13 21:46:58 CST 2025
     */
    int insertSelective(WorkoutLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workout_log
     *
     * @mbg.generated Sun Apr 13 21:46:58 CST 2025
     */
    List<WorkoutLog> selectByExampleWithBLOBs(WorkoutLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workout_log
     *
     * @mbg.generated Sun Apr 13 21:46:58 CST 2025
     */
    List<WorkoutLog> selectByExample(WorkoutLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workout_log
     *
     * @mbg.generated Sun Apr 13 21:46:58 CST 2025
     */
    WorkoutLog selectByPrimaryKey(Integer workoutlogid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workout_log
     *
     * @mbg.generated Sun Apr 13 21:46:58 CST 2025
     */
    int updateByExampleSelective(@Param("record") WorkoutLog record, @Param("example") WorkoutLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workout_log
     *
     * @mbg.generated Sun Apr 13 21:46:58 CST 2025
     */
    int updateByExampleWithBLOBs(@Param("record") WorkoutLog record, @Param("example") WorkoutLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workout_log
     *
     * @mbg.generated Sun Apr 13 21:46:58 CST 2025
     */
    int updateByExample(@Param("record") WorkoutLog record, @Param("example") WorkoutLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workout_log
     *
     * @mbg.generated Sun Apr 13 21:46:58 CST 2025
     */
    int updateByPrimaryKeySelective(WorkoutLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workout_log
     *
     * @mbg.generated Sun Apr 13 21:46:58 CST 2025
     */
    int updateByPrimaryKeyWithBLOBs(WorkoutLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workout_log
     *
     * @mbg.generated Sun Apr 13 21:46:58 CST 2025
     */
    int updateByPrimaryKey(WorkoutLog record);
}