package com.liu.gymmanagement.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class AccesslogsExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table accesslogs
     *
     * @mbg.generated Wed Mar 26 00:44:02 CST 2025
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table accesslogs
     *
     * @mbg.generated Wed Mar 26 00:44:02 CST 2025
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table accesslogs
     *
     * @mbg.generated Wed Mar 26 00:44:02 CST 2025
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accesslogs
     *
     * @mbg.generated Wed Mar 26 00:44:02 CST 2025
     */
    public AccesslogsExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accesslogs
     *
     * @mbg.generated Wed Mar 26 00:44:02 CST 2025
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accesslogs
     *
     * @mbg.generated Wed Mar 26 00:44:02 CST 2025
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accesslogs
     *
     * @mbg.generated Wed Mar 26 00:44:02 CST 2025
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accesslogs
     *
     * @mbg.generated Wed Mar 26 00:44:02 CST 2025
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accesslogs
     *
     * @mbg.generated Wed Mar 26 00:44:02 CST 2025
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accesslogs
     *
     * @mbg.generated Wed Mar 26 00:44:02 CST 2025
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accesslogs
     *
     * @mbg.generated Wed Mar 26 00:44:02 CST 2025
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accesslogs
     *
     * @mbg.generated Wed Mar 26 00:44:02 CST 2025
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accesslogs
     *
     * @mbg.generated Wed Mar 26 00:44:02 CST 2025
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accesslogs
     *
     * @mbg.generated Wed Mar 26 00:44:02 CST 2025
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table accesslogs
     *
     * @mbg.generated Wed Mar 26 00:44:02 CST 2025
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andLogidIsNull() {
            addCriterion("LogID is null");
            return (Criteria) this;
        }

        public Criteria andLogidIsNotNull() {
            addCriterion("LogID is not null");
            return (Criteria) this;
        }

        public Criteria andLogidEqualTo(Integer value) {
            addCriterion("LogID =", value, "logid");
            return (Criteria) this;
        }

        public Criteria andLogidNotEqualTo(Integer value) {
            addCriterion("LogID <>", value, "logid");
            return (Criteria) this;
        }

        public Criteria andLogidGreaterThan(Integer value) {
            addCriterion("LogID >", value, "logid");
            return (Criteria) this;
        }

        public Criteria andLogidGreaterThanOrEqualTo(Integer value) {
            addCriterion("LogID >=", value, "logid");
            return (Criteria) this;
        }

        public Criteria andLogidLessThan(Integer value) {
            addCriterion("LogID <", value, "logid");
            return (Criteria) this;
        }

        public Criteria andLogidLessThanOrEqualTo(Integer value) {
            addCriterion("LogID <=", value, "logid");
            return (Criteria) this;
        }

        public Criteria andLogidIn(List<Integer> values) {
            addCriterion("LogID in", values, "logid");
            return (Criteria) this;
        }

        public Criteria andLogidNotIn(List<Integer> values) {
            addCriterion("LogID not in", values, "logid");
            return (Criteria) this;
        }

        public Criteria andLogidBetween(Integer value1, Integer value2) {
            addCriterion("LogID between", value1, value2, "logid");
            return (Criteria) this;
        }

        public Criteria andLogidNotBetween(Integer value1, Integer value2) {
            addCriterion("LogID not between", value1, value2, "logid");
            return (Criteria) this;
        }

        public Criteria andUseridIsNull() {
            addCriterion("UserID is null");
            return (Criteria) this;
        }

        public Criteria andUseridIsNotNull() {
            addCriterion("UserID is not null");
            return (Criteria) this;
        }

        public Criteria andUseridEqualTo(String value) {
            addCriterion("UserID =", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotEqualTo(String value) {
            addCriterion("UserID <>", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridGreaterThan(String value) {
            addCriterion("UserID >", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridGreaterThanOrEqualTo(String value) {
            addCriterion("UserID >=", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLessThan(String value) {
            addCriterion("UserID <", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLessThanOrEqualTo(String value) {
            addCriterion("UserID <=", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLike(String value) {
            addCriterion("UserID like", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotLike(String value) {
            addCriterion("UserID not like", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridIn(List<String> values) {
            addCriterion("UserID in", values, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotIn(List<String> values) {
            addCriterion("UserID not in", values, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridBetween(String value1, String value2) {
            addCriterion("UserID between", value1, value2, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotBetween(String value1, String value2) {
            addCriterion("UserID not between", value1, value2, "userid");
            return (Criteria) this;
        }

        public Criteria andGymidIsNull() {
            addCriterion("GymID is null");
            return (Criteria) this;
        }

        public Criteria andGymidIsNotNull() {
            addCriterion("GymID is not null");
            return (Criteria) this;
        }

        public Criteria andGymidEqualTo(Integer value) {
            addCriterion("GymID =", value, "gymid");
            return (Criteria) this;
        }

        public Criteria andGymidNotEqualTo(Integer value) {
            addCriterion("GymID <>", value, "gymid");
            return (Criteria) this;
        }

        public Criteria andGymidGreaterThan(Integer value) {
            addCriterion("GymID >", value, "gymid");
            return (Criteria) this;
        }

        public Criteria andGymidGreaterThanOrEqualTo(Integer value) {
            addCriterion("GymID >=", value, "gymid");
            return (Criteria) this;
        }

        public Criteria andGymidLessThan(Integer value) {
            addCriterion("GymID <", value, "gymid");
            return (Criteria) this;
        }

        public Criteria andGymidLessThanOrEqualTo(Integer value) {
            addCriterion("GymID <=", value, "gymid");
            return (Criteria) this;
        }

        public Criteria andGymidIn(List<Integer> values) {
            addCriterion("GymID in", values, "gymid");
            return (Criteria) this;
        }

        public Criteria andGymidNotIn(List<Integer> values) {
            addCriterion("GymID not in", values, "gymid");
            return (Criteria) this;
        }

        public Criteria andGymidBetween(Integer value1, Integer value2) {
            addCriterion("GymID between", value1, value2, "gymid");
            return (Criteria) this;
        }

        public Criteria andGymidNotBetween(Integer value1, Integer value2) {
            addCriterion("GymID not between", value1, value2, "gymid");
            return (Criteria) this;
        }

        public Criteria andEntrytimeIsNull() {
            addCriterion("EntryTime is null");
            return (Criteria) this;
        }

        public Criteria andEntrytimeIsNotNull() {
            addCriterion("EntryTime is not null");
            return (Criteria) this;
        }

        public Criteria andEntrytimeEqualTo(Date value) {
            addCriterion("EntryTime =", value, "entrytime");
            return (Criteria) this;
        }

        public Criteria andEntrytimeNotEqualTo(Date value) {
            addCriterion("EntryTime <>", value, "entrytime");
            return (Criteria) this;
        }

        public Criteria andEntrytimeGreaterThan(Date value) {
            addCriterion("EntryTime >", value, "entrytime");
            return (Criteria) this;
        }

        public Criteria andEntrytimeGreaterThanOrEqualTo(Date value) {
            addCriterion("EntryTime >=", value, "entrytime");
            return (Criteria) this;
        }

        public Criteria andEntrytimeLessThan(Date value) {
            addCriterion("EntryTime <", value, "entrytime");
            return (Criteria) this;
        }

        public Criteria andEntrytimeLessThanOrEqualTo(Date value) {
            addCriterion("EntryTime <=", value, "entrytime");
            return (Criteria) this;
        }

        public Criteria andEntrytimeIn(List<Date> values) {
            addCriterion("EntryTime in", values, "entrytime");
            return (Criteria) this;
        }

        public Criteria andEntrytimeNotIn(List<Date> values) {
            addCriterion("EntryTime not in", values, "entrytime");
            return (Criteria) this;
        }

        public Criteria andEntrytimeBetween(Date value1, Date value2) {
            addCriterion("EntryTime between", value1, value2, "entrytime");
            return (Criteria) this;
        }

        public Criteria andEntrytimeNotBetween(Date value1, Date value2) {
            addCriterion("EntryTime not between", value1, value2, "entrytime");
            return (Criteria) this;
        }

        public Criteria andExittimeIsNull() {
            addCriterion("ExitTime is null");
            return (Criteria) this;
        }

        public Criteria andExittimeIsNotNull() {
            addCriterion("ExitTime is not null");
            return (Criteria) this;
        }

        public Criteria andExittimeEqualTo(Date value) {
            addCriterion("ExitTime =", value, "exittime");
            return (Criteria) this;
        }

        public Criteria andExittimeNotEqualTo(Date value) {
            addCriterion("ExitTime <>", value, "exittime");
            return (Criteria) this;
        }

        public Criteria andExittimeGreaterThan(Date value) {
            addCriterion("ExitTime >", value, "exittime");
            return (Criteria) this;
        }

        public Criteria andExittimeGreaterThanOrEqualTo(Date value) {
            addCriterion("ExitTime >=", value, "exittime");
            return (Criteria) this;
        }

        public Criteria andExittimeLessThan(Date value) {
            addCriterion("ExitTime <", value, "exittime");
            return (Criteria) this;
        }

        public Criteria andExittimeLessThanOrEqualTo(Date value) {
            addCriterion("ExitTime <=", value, "exittime");
            return (Criteria) this;
        }

        public Criteria andExittimeIn(List<Date> values) {
            addCriterion("ExitTime in", values, "exittime");
            return (Criteria) this;
        }

        public Criteria andExittimeNotIn(List<Date> values) {
            addCriterion("ExitTime not in", values, "exittime");
            return (Criteria) this;
        }

        public Criteria andExittimeBetween(Date value1, Date value2) {
            addCriterion("ExitTime between", value1, value2, "exittime");
            return (Criteria) this;
        }

        public Criteria andExittimeNotBetween(Date value1, Date value2) {
            addCriterion("ExitTime not between", value1, value2, "exittime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table accesslogs
     *
     * @mbg.generated do_not_delete_during_merge Wed Mar 26 00:44:02 CST 2025
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table accesslogs
     *
     * @mbg.generated Wed Mar 26 00:44:02 CST 2025
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}