package com.liu.gymmanagement.model;

import jakarta.persistence.Entity;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.Date;

public class Accesslogs {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accesslogs.LogID
     *
     * @mbg.generated Wed Mar 26 00:44:02 CST 2025
     */
    private Integer logid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accesslogs.UserID
     *
     * @mbg.generated Wed Mar 26 00:44:02 CST 2025
     */
    private String userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accesslogs.GymID
     *
     * @mbg.generated Wed Mar 26 00:44:02 CST 2025
     */
    private Integer gymid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accesslogs.EntryTime
     *
     * @mbg.generated Wed Mar 26 00:44:02 CST 2025
     */
    private LocalDateTime entrytime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accesslogs.ExitTime
     *
     * @mbg.generated Wed Mar 26 00:44:02 CST 2025
     */
    private LocalDateTime exittime;

    public Accesslogs(String userId, Integer gymId, LocalDateTime entryTime, LocalDateTime exitTime) {
        this.userid = userId;
        this.gymid = gymId;
        this.entrytime = entryTime;
        this.exittime = exitTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accesslogs.LogID
     *
     * @return the value of accesslogs.LogID
     *
     * @mbg.generated Wed Mar 26 00:44:02 CST 2025
     */
    public Integer getLogid() {
        return logid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accesslogs.LogID
     *
     * @param logid the value for accesslogs.LogID
     *
     * @mbg.generated Wed Mar 26 00:44:02 CST 2025
     */
    public void setLogid(Integer logid) {
        this.logid = logid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accesslogs.UserID
     *
     * @return the value of accesslogs.UserID
     *
     * @mbg.generated Wed Mar 26 00:44:02 CST 2025
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accesslogs.UserID
     *
     * @param userid the value for accesslogs.UserID
     *
     * @mbg.generated Wed Mar 26 00:44:02 CST 2025
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accesslogs.GymID
     *
     * @return the value of accesslogs.GymID
     *
     * @mbg.generated Wed Mar 26 00:44:02 CST 2025
     */
    public Integer getGymid() {
        return gymid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accesslogs.GymID
     *
     * @param gymid the value for accesslogs.GymID
     *
     * @mbg.generated Wed Mar 26 00:44:02 CST 2025
     */
    public void setGymid(Integer gymid) {
        this.gymid = gymid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accesslogs.EntryTime
     *
     * @return the value of accesslogs.EntryTime
     *
     * @mbg.generated Wed Mar 26 00:44:02 CST 2025
     */
    public LocalDateTime getEntrytime() {
        return entrytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accesslogs.EntryTime
     *
     * @param entrytime the value for accesslogs.EntryTime
     *
     * @mbg.generated Wed Mar 26 00:44:02 CST 2025
     */
    public void setEntrytime(LocalDateTime entrytime) {
        this.entrytime = entrytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accesslogs.ExitTime
     *
     * @return the value of accesslogs.ExitTime
     *
     * @mbg.generated Wed Mar 26 00:44:02 CST 2025
     */
    public LocalDateTime getExittime() {
        return exittime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accesslogs.ExitTime
     *
     * @param exittime the value for accesslogs.ExitTime
     *
     * @mbg.generated Wed Mar 26 00:44:02 CST 2025
     */
    public void setExittime(LocalDateTime exittime) {
        this.exittime = exittime;
    }
}