package com.liu.gymmanagement.model;

import java.util.Date;

public class CapacityConfig {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column capacity_config.config_id
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    private Integer configId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column capacity_config.GymID
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    private Integer gymid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column capacity_config.max_capacity
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    private Integer maxCapacity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column capacity_config.start_time
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    private Date startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column capacity_config.end_time
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    private Date endTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column capacity_config.config_id
     *
     * @return the value of capacity_config.config_id
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    public Integer getConfigId() {
        return configId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column capacity_config.config_id
     *
     * @param configId the value for capacity_config.config_id
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    public void setConfigId(Integer configId) {
        this.configId = configId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column capacity_config.GymID
     *
     * @return the value of capacity_config.GymID
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    public Integer getGymid() {
        return gymid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column capacity_config.GymID
     *
     * @param gymid the value for capacity_config.GymID
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    public void setGymid(Integer gymid) {
        this.gymid = gymid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column capacity_config.max_capacity
     *
     * @return the value of capacity_config.max_capacity
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    public Integer getMaxCapacity() {
        return maxCapacity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column capacity_config.max_capacity
     *
     * @param maxCapacity the value for capacity_config.max_capacity
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    public void setMaxCapacity(Integer maxCapacity) {
        this.maxCapacity = maxCapacity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column capacity_config.start_time
     *
     * @return the value of capacity_config.start_time
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column capacity_config.start_time
     *
     * @param startTime the value for capacity_config.start_time
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column capacity_config.end_time
     *
     * @return the value of capacity_config.end_time
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column capacity_config.end_time
     *
     * @param endTime the value for capacity_config.end_time
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }
}