package com.liu.gymmanagement.model;

import java.util.Date;

public class EquipmentStatus {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column equipmentstatus.StatusID
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    private Integer statusid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column equipmentstatus.EquipmentID
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    private Integer equipmentid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column equipmentstatus.Status
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column equipmentstatus.Timestamp
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    private Date timestamp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column equipmentstatus.StatusID
     *
     * @return the value of equipmentstatus.StatusID
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    public Integer getStatusid() {
        return statusid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column equipmentstatus.StatusID
     *
     * @param statusid the value for equipmentstatus.StatusID
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    public void setStatusid(Integer statusid) {
        this.statusid = statusid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column equipmentstatus.EquipmentID
     *
     * @return the value of equipmentstatus.EquipmentID
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    public Integer getEquipmentid() {
        return equipmentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column equipmentstatus.EquipmentID
     *
     * @param equipmentid the value for equipmentstatus.EquipmentID
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    public void setEquipmentid(Integer equipmentid) {
        this.equipmentid = equipmentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column equipmentstatus.Status
     *
     * @return the value of equipmentstatus.Status
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column equipmentstatus.Status
     *
     * @param status the value for equipmentstatus.Status
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column equipmentstatus.Timestamp
     *
     * @return the value of equipmentstatus.Timestamp
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    public Date getTimestamp() {
        return timestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column equipmentstatus.Timestamp
     *
     * @param timestamp the value for equipmentstatus.Timestamp
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    public void setTimestamp(Date timestamp) {
        this.timestamp = timestamp;
    }
}