package com.liu.gymmanagement.model;

public class Equipment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column equipment.EquipmentID
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    private Integer equipmentid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column equipment.Name
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column equipment.GymID
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    private Integer gymid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column equipment.Description
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column equipment.EquipmentID
     *
     * @return the value of equipment.EquipmentID
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    public Integer getEquipmentid() {
        return equipmentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column equipment.EquipmentID
     *
     * @param equipmentid the value for equipment.EquipmentID
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    public void setEquipmentid(Integer equipmentid) {
        this.equipmentid = equipmentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column equipment.Name
     *
     * @return the value of equipment.Name
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column equipment.Name
     *
     * @param name the value for equipment.Name
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column equipment.GymID
     *
     * @return the value of equipment.GymID
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    public Integer getGymid() {
        return gymid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column equipment.GymID
     *
     * @param gymid the value for equipment.GymID
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    public void setGymid(Integer gymid) {
        this.gymid = gymid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column equipment.Description
     *
     * @return the value of equipment.Description
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column equipment.Description
     *
     * @param description the value for equipment.Description
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}