package com.liu.gymmanagement.model;

import java.util.Date;

public class Feedback {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feedbacks.FeedbackID
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    private Integer feedbackid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feedbacks.UserID
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    private String userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feedbacks.Category
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    private String category;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feedbacks.Timestamp
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    private Date timestamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feedbacks.Content
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedbacks.FeedbackID
     *
     * @return the value of feedbacks.FeedbackID
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    public Integer getFeedbackid() {
        return feedbackid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feedbacks.FeedbackID
     *
     * @param feedbackid the value for feedbacks.FeedbackID
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    public void setFeedbackid(Integer feedbackid) {
        this.feedbackid = feedbackid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedbacks.UserID
     *
     * @return the value of feedbacks.UserID
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feedbacks.UserID
     *
     * @param userid the value for feedbacks.UserID
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedbacks.Category
     *
     * @return the value of feedbacks.Category
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feedbacks.Category
     *
     * @param category the value for feedbacks.Category
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    public void setCategory(String category) {
        this.category = category == null ? null : category.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedbacks.Timestamp
     *
     * @return the value of feedbacks.Timestamp
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    public Date getTimestamp() {
        return timestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feedbacks.Timestamp
     *
     * @param timestamp the value for feedbacks.Timestamp
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    public void setTimestamp(Date timestamp) {
        this.timestamp = timestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedbacks.Content
     *
     * @return the value of feedbacks.Content
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feedbacks.Content
     *
     * @param content the value for feedbacks.Content
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}