package com.liu.gymmanagement.model;

import java.time.LocalTime;
import java.util.Date;

public class GymTimeslotTemplate {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gym_timeslot_template.id
     *
     * @mbg.generated Fri Mar 21 03:45:11 CST 2025
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gym_timeslot_template.GymID
     *
     * @mbg.generated Fri Mar 21 03:45:11 CST 2025
     */
    private Integer gymid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gym_timeslot_template.start_time
     *
     * @mbg.generated Fri Mar 21 03:45:11 CST 2025
     */
    private LocalTime startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gym_timeslot_template.end_time
     *
     * @mbg.generated Fri Mar 21 03:45:11 CST 2025
     */
    private LocalTime endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gym_timeslot_template.max_capacity
     *
     * @mbg.generated Fri Mar 21 03:45:11 CST 2025
     */
    private Integer maxCapacity;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gym_timeslot_template.id
     *
     * @return the value of gym_timeslot_template.id
     *
     * @mbg.generated Fri Mar 21 03:45:11 CST 2025
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gym_timeslot_template.id
     *
     * @param id the value for gym_timeslot_template.id
     *
     * @mbg.generated Fri Mar 21 03:45:11 CST 2025
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gym_timeslot_template.GymID
     *
     * @return the value of gym_timeslot_template.GymID
     *
     * @mbg.generated Fri Mar 21 03:45:11 CST 2025
     */
    public Integer getGymid() {
        return gymid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gym_timeslot_template.GymID
     *
     * @param gymid the value for gym_timeslot_template.GymID
     *
     * @mbg.generated Fri Mar 21 03:45:11 CST 2025
     */
    public void setGymid(Integer gymid) {
        this.gymid = gymid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gym_timeslot_template.start_time
     *
     * @return the value of gym_timeslot_template.start_time
     *
     * @mbg.generated Fri Mar 21 03:45:11 CST 2025
     */
    public LocalTime getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gym_timeslot_template.start_time
     *
     * @param startTime the value for gym_timeslot_template.start_time
     *
     * @mbg.generated Fri Mar 21 03:45:11 CST 2025
     */
    public void setStartTime(LocalTime startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gym_timeslot_template.end_time
     *
     * @return the value of gym_timeslot_template.end_time
     *
     * @mbg.generated Fri Mar 21 03:45:11 CST 2025
     */
    public LocalTime getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gym_timeslot_template.end_time
     *
     * @param endTime the value for gym_timeslot_template.end_time
     *
     * @mbg.generated Fri Mar 21 03:45:11 CST 2025
     */
    public void setEndTime(LocalTime endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gym_timeslot_template.max_capacity
     *
     * @return the value of gym_timeslot_template.max_capacity
     *
     * @mbg.generated Fri Mar 21 03:45:11 CST 2025
     */
    public Integer getMaxCapacity() {
        return maxCapacity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gym_timeslot_template.max_capacity
     *
     * @param maxCapacity the value for gym_timeslot_template.max_capacity
     *
     * @mbg.generated Fri Mar 21 03:45:11 CST 2025
     */
    public void setMaxCapacity(Integer maxCapacity) {
        this.maxCapacity = maxCapacity;
    }
}