package com.liu.gymmanagement.model;

import java.util.Date;

public class Notification {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notifications.NotificationID
     *
     * @mbg.generated Mon Apr 14 19:16:48 CST 2025
     */
    private Integer notificationid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notifications.UserID
     *
     * @mbg.generated Mon Apr 14 19:16:48 CST 2025
     */
    private String userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notifications.Type
     *
     * @mbg.generated Mon Apr 14 19:16:48 CST 2025
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notifications.Timestamp
     *
     * @mbg.generated Mon Apr 14 19:16:48 CST 2025
     */
    private Date timestamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notifications.Message
     *
     * @mbg.generated Mon Apr 14 19:16:48 CST 2025
     */
    private String message;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notifications.NotificationID
     *
     * @return the value of notifications.NotificationID
     *
     * @mbg.generated Mon Apr 14 19:16:48 CST 2025
     */
    public Integer getNotificationid() {
        return notificationid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notifications.NotificationID
     *
     * @param notificationid the value for notifications.NotificationID
     *
     * @mbg.generated Mon Apr 14 19:16:48 CST 2025
     */
    public void setNotificationid(Integer notificationid) {
        this.notificationid = notificationid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notifications.UserID
     *
     * @return the value of notifications.UserID
     *
     * @mbg.generated Mon Apr 14 19:16:48 CST 2025
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notifications.UserID
     *
     * @param userid the value for notifications.UserID
     *
     * @mbg.generated Mon Apr 14 19:16:48 CST 2025
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notifications.Type
     *
     * @return the value of notifications.Type
     *
     * @mbg.generated Mon Apr 14 19:16:48 CST 2025
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notifications.Type
     *
     * @param type the value for notifications.Type
     *
     * @mbg.generated Mon Apr 14 19:16:48 CST 2025
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notifications.Timestamp
     *
     * @return the value of notifications.Timestamp
     *
     * @mbg.generated Mon Apr 14 19:16:48 CST 2025
     */
    public Date getTimestamp() {
        return timestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notifications.Timestamp
     *
     * @param timestamp the value for notifications.Timestamp
     *
     * @mbg.generated Mon Apr 14 19:16:48 CST 2025
     */
    public void setTimestamp(Date timestamp) {
        this.timestamp = timestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notifications.Message
     *
     * @return the value of notifications.Message
     *
     * @mbg.generated Mon Apr 14 19:16:48 CST 2025
     */
    public String getMessage() {
        return message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notifications.Message
     *
     * @param message the value for notifications.Message
     *
     * @mbg.generated Mon Apr 14 19:16:48 CST 2025
     */
    public void setMessage(String message) {
        this.message = message == null ? null : message.trim();
    }
}