package com.liu.gymmanagement.model;

import java.util.Date;

public class Report {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reports.ReportID
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    private Integer reportid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reports.UserID
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    private String userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reports.EquipmentID
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    private Integer equipmentid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reports.Status
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reports.Timestamp
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    private Date timestamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reports.Description
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reports.ReportID
     *
     * @return the value of reports.ReportID
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    public Integer getReportid() {
        return reportid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reports.ReportID
     *
     * @param reportid the value for reports.ReportID
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    public void setReportid(Integer reportid) {
        this.reportid = reportid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reports.UserID
     *
     * @return the value of reports.UserID
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reports.UserID
     *
     * @param userid the value for reports.UserID
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reports.EquipmentID
     *
     * @return the value of reports.EquipmentID
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    public Integer getEquipmentid() {
        return equipmentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reports.EquipmentID
     *
     * @param equipmentid the value for reports.EquipmentID
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    public void setEquipmentid(Integer equipmentid) {
        this.equipmentid = equipmentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reports.Status
     *
     * @return the value of reports.Status
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reports.Status
     *
     * @param status the value for reports.Status
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reports.Timestamp
     *
     * @return the value of reports.Timestamp
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    public Date getTimestamp() {
        return timestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reports.Timestamp
     *
     * @param timestamp the value for reports.Timestamp
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    public void setTimestamp(Date timestamp) {
        this.timestamp = timestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reports.Description
     *
     * @return the value of reports.Description
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reports.Description
     *
     * @param description the value for reports.Description
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}