package com.liu.gymmanagement.model;

import java.time.LocalDateTime;
import java.time.ZoneId;
import java.util.Date;

public class Reservation {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reservations.ReservationID
     *
     * @mbg.generated Thu Mar 20 22:59:52 CST 2025
     */
    private Integer reservationid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reservations.UserID
     *
     * @mbg.generated Thu Mar 20 22:59:52 CST 2025
     */
    private String userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reservations.GymID
     *
     * @mbg.generated Thu Mar 20 22:59:52 CST 2025
     */
    private Integer gymid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reservations.TimeslotID
     *
     * @mbg.generated Thu Mar 20 22:59:52 CST 2025
     */
    private Integer timeslotid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reservations.reservation_time
     *
     * @mbg.generated Thu Mar 20 22:59:52 CST 2025
     */
    private LocalDateTime reservationTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reservations.status
     *
     * @mbg.generated Thu Mar 20 22:59:52 CST 2025
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reservations.qr_code
     *
     * @mbg.generated Thu Mar 20 22:59:52 CST 2025
     */
    private String qrCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reservations.ReservationID
     *
     * @return the value of reservations.ReservationID
     *
     * @mbg.generated Thu Mar 20 22:59:52 CST 2025
     */
    // 判断预约是否可以取消
    public boolean isCancellable() {
        // 获取当前时间的毫秒值
        long currentTime = System.currentTimeMillis();

        // 获取预约时间的毫秒值
        long startTime = reservationTime.atZone(ZoneId.systemDefault()).toInstant().toEpochMilli(); // 转换为毫秒时间戳

        // 判断是否在预约开始前30分钟以内
        return (startTime - currentTime) > 30 * 60 * 1000; // 可以取消
    }

    public Integer getReservationid() {
        return reservationid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reservations.ReservationID
     *
     * @param reservationid the value for reservations.ReservationID
     *
     * @mbg.generated Thu Mar 20 22:59:52 CST 2025
     */
    public void setReservationid(Integer reservationid) {
        this.reservationid = reservationid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reservations.UserID
     *
     * @return the value of reservations.UserID
     *
     * @mbg.generated Thu Mar 20 22:59:52 CST 2025
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reservations.UserID
     *
     * @param userid the value for reservations.UserID
     *
     * @mbg.generated Thu Mar 20 22:59:52 CST 2025
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reservations.GymID
     *
     * @return the value of reservations.GymID
     *
     * @mbg.generated Thu Mar 20 22:59:52 CST 2025
     */
    public Integer getGymid() {
        return gymid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reservations.GymID
     *
     * @param gymid the value for reservations.GymID
     *
     * @mbg.generated Thu Mar 20 22:59:52 CST 2025
     */
    public void setGymid(Integer gymid) {
        this.gymid = gymid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reservations.TimeslotID
     *
     * @return the value of reservations.TimeslotID
     *
     * @mbg.generated Thu Mar 20 22:59:52 CST 2025
     */
    public Integer getTimeslotid() {
        return timeslotid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reservations.TimeslotID
     *
     * @param timeslotid the value for reservations.TimeslotID
     *
     * @mbg.generated Thu Mar 20 22:59:52 CST 2025
     */
    public void setTimeslotid(Integer timeslotid) {
        this.timeslotid = timeslotid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reservations.reservation_time
     *
     * @return the value of reservations.reservation_time
     * @mbg.generated Thu Mar 20 22:59:52 CST 2025
     */
    public LocalDateTime getReservationTime() {
        return reservationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reservations.reservation_time
     *
     * @param reservationTime the value for reservations.reservation_time
     *
     * @mbg.generated Thu Mar 20 22:59:52 CST 2025
     */
    public void setReservationTime(LocalDateTime reservationTime) {
        this.reservationTime = reservationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reservations.status
     *
     * @return the value of reservations.status
     *
     * @mbg.generated Thu Mar 20 22:59:52 CST 2025
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reservations.status
     *
     * @param status the value for reservations.status
     *
     * @mbg.generated Thu Mar 20 22:59:52 CST 2025
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reservations.qr_code
     *
     * @return the value of reservations.qr_code
     *
     * @mbg.generated Thu Mar 20 22:59:52 CST 2025
     */
    public String getQrCode() {
        return qrCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reservations.qr_code
     *
     * @param qrCode the value for reservations.qr_code
     *
     * @mbg.generated Thu Mar 20 22:59:52 CST 2025
     */
    public void setQrCode(String qrCode) {
        this.qrCode = qrCode == null ? null : qrCode.trim();
    }
}