package com.liu.gymmanagement.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ReservationExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table reservations
     *
     * @mbg.generated Wed Mar 26 00:44:02 CST 2025
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table reservations
     *
     * @mbg.generated Wed Mar 26 00:44:02 CST 2025
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table reservations
     *
     * @mbg.generated Wed Mar 26 00:44:02 CST 2025
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reservations
     *
     * @mbg.generated Wed Mar 26 00:44:02 CST 2025
     */
    public ReservationExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reservations
     *
     * @mbg.generated Wed Mar 26 00:44:02 CST 2025
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reservations
     *
     * @mbg.generated Wed Mar 26 00:44:02 CST 2025
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reservations
     *
     * @mbg.generated Wed Mar 26 00:44:02 CST 2025
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reservations
     *
     * @mbg.generated Wed Mar 26 00:44:02 CST 2025
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reservations
     *
     * @mbg.generated Wed Mar 26 00:44:02 CST 2025
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reservations
     *
     * @mbg.generated Wed Mar 26 00:44:02 CST 2025
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reservations
     *
     * @mbg.generated Wed Mar 26 00:44:02 CST 2025
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reservations
     *
     * @mbg.generated Wed Mar 26 00:44:02 CST 2025
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reservations
     *
     * @mbg.generated Wed Mar 26 00:44:02 CST 2025
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reservations
     *
     * @mbg.generated Wed Mar 26 00:44:02 CST 2025
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table reservations
     *
     * @mbg.generated Wed Mar 26 00:44:02 CST 2025
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andReservationidIsNull() {
            addCriterion("ReservationID is null");
            return (Criteria) this;
        }

        public Criteria andReservationidIsNotNull() {
            addCriterion("ReservationID is not null");
            return (Criteria) this;
        }

        public Criteria andReservationidEqualTo(Integer value) {
            addCriterion("ReservationID =", value, "reservationid");
            return (Criteria) this;
        }

        public Criteria andReservationidNotEqualTo(Integer value) {
            addCriterion("ReservationID <>", value, "reservationid");
            return (Criteria) this;
        }

        public Criteria andReservationidGreaterThan(Integer value) {
            addCriterion("ReservationID >", value, "reservationid");
            return (Criteria) this;
        }

        public Criteria andReservationidGreaterThanOrEqualTo(Integer value) {
            addCriterion("ReservationID >=", value, "reservationid");
            return (Criteria) this;
        }

        public Criteria andReservationidLessThan(Integer value) {
            addCriterion("ReservationID <", value, "reservationid");
            return (Criteria) this;
        }

        public Criteria andReservationidLessThanOrEqualTo(Integer value) {
            addCriterion("ReservationID <=", value, "reservationid");
            return (Criteria) this;
        }

        public Criteria andReservationidIn(List<Integer> values) {
            addCriterion("ReservationID in", values, "reservationid");
            return (Criteria) this;
        }

        public Criteria andReservationidNotIn(List<Integer> values) {
            addCriterion("ReservationID not in", values, "reservationid");
            return (Criteria) this;
        }

        public Criteria andReservationidBetween(Integer value1, Integer value2) {
            addCriterion("ReservationID between", value1, value2, "reservationid");
            return (Criteria) this;
        }

        public Criteria andReservationidNotBetween(Integer value1, Integer value2) {
            addCriterion("ReservationID not between", value1, value2, "reservationid");
            return (Criteria) this;
        }

        public Criteria andUseridIsNull() {
            addCriterion("UserID is null");
            return (Criteria) this;
        }

        public Criteria andUseridIsNotNull() {
            addCriterion("UserID is not null");
            return (Criteria) this;
        }

        public Criteria andUseridEqualTo(String value) {
            addCriterion("UserID =", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotEqualTo(String value) {
            addCriterion("UserID <>", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridGreaterThan(String value) {
            addCriterion("UserID >", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridGreaterThanOrEqualTo(String value) {
            addCriterion("UserID >=", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLessThan(String value) {
            addCriterion("UserID <", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLessThanOrEqualTo(String value) {
            addCriterion("UserID <=", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLike(String value) {
            addCriterion("UserID like", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotLike(String value) {
            addCriterion("UserID not like", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridIn(List<String> values) {
            addCriterion("UserID in", values, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotIn(List<String> values) {
            addCriterion("UserID not in", values, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridBetween(String value1, String value2) {
            addCriterion("UserID between", value1, value2, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotBetween(String value1, String value2) {
            addCriterion("UserID not between", value1, value2, "userid");
            return (Criteria) this;
        }

        public Criteria andGymidIsNull() {
            addCriterion("GymID is null");
            return (Criteria) this;
        }

        public Criteria andGymidIsNotNull() {
            addCriterion("GymID is not null");
            return (Criteria) this;
        }

        public Criteria andGymidEqualTo(Integer value) {
            addCriterion("GymID =", value, "gymid");
            return (Criteria) this;
        }

        public Criteria andGymidNotEqualTo(Integer value) {
            addCriterion("GymID <>", value, "gymid");
            return (Criteria) this;
        }

        public Criteria andGymidGreaterThan(Integer value) {
            addCriterion("GymID >", value, "gymid");
            return (Criteria) this;
        }

        public Criteria andGymidGreaterThanOrEqualTo(Integer value) {
            addCriterion("GymID >=", value, "gymid");
            return (Criteria) this;
        }

        public Criteria andGymidLessThan(Integer value) {
            addCriterion("GymID <", value, "gymid");
            return (Criteria) this;
        }

        public Criteria andGymidLessThanOrEqualTo(Integer value) {
            addCriterion("GymID <=", value, "gymid");
            return (Criteria) this;
        }

        public Criteria andGymidIn(List<Integer> values) {
            addCriterion("GymID in", values, "gymid");
            return (Criteria) this;
        }

        public Criteria andGymidNotIn(List<Integer> values) {
            addCriterion("GymID not in", values, "gymid");
            return (Criteria) this;
        }

        public Criteria andGymidBetween(Integer value1, Integer value2) {
            addCriterion("GymID between", value1, value2, "gymid");
            return (Criteria) this;
        }

        public Criteria andGymidNotBetween(Integer value1, Integer value2) {
            addCriterion("GymID not between", value1, value2, "gymid");
            return (Criteria) this;
        }

        public Criteria andTimeslotidIsNull() {
            addCriterion("TimeslotID is null");
            return (Criteria) this;
        }

        public Criteria andTimeslotidIsNotNull() {
            addCriterion("TimeslotID is not null");
            return (Criteria) this;
        }

        public Criteria andTimeslotidEqualTo(Integer value) {
            addCriterion("TimeslotID =", value, "timeslotid");
            return (Criteria) this;
        }

        public Criteria andTimeslotidNotEqualTo(Integer value) {
            addCriterion("TimeslotID <>", value, "timeslotid");
            return (Criteria) this;
        }

        public Criteria andTimeslotidGreaterThan(Integer value) {
            addCriterion("TimeslotID >", value, "timeslotid");
            return (Criteria) this;
        }

        public Criteria andTimeslotidGreaterThanOrEqualTo(Integer value) {
            addCriterion("TimeslotID >=", value, "timeslotid");
            return (Criteria) this;
        }

        public Criteria andTimeslotidLessThan(Integer value) {
            addCriterion("TimeslotID <", value, "timeslotid");
            return (Criteria) this;
        }

        public Criteria andTimeslotidLessThanOrEqualTo(Integer value) {
            addCriterion("TimeslotID <=", value, "timeslotid");
            return (Criteria) this;
        }

        public Criteria andTimeslotidIn(List<Integer> values) {
            addCriterion("TimeslotID in", values, "timeslotid");
            return (Criteria) this;
        }

        public Criteria andTimeslotidNotIn(List<Integer> values) {
            addCriterion("TimeslotID not in", values, "timeslotid");
            return (Criteria) this;
        }

        public Criteria andTimeslotidBetween(Integer value1, Integer value2) {
            addCriterion("TimeslotID between", value1, value2, "timeslotid");
            return (Criteria) this;
        }

        public Criteria andTimeslotidNotBetween(Integer value1, Integer value2) {
            addCriterion("TimeslotID not between", value1, value2, "timeslotid");
            return (Criteria) this;
        }

        public Criteria andReservationTimeIsNull() {
            addCriterion("reservation_time is null");
            return (Criteria) this;
        }

        public Criteria andReservationTimeIsNotNull() {
            addCriterion("reservation_time is not null");
            return (Criteria) this;
        }

        public Criteria andReservationTimeEqualTo(Date value) {
            addCriterion("reservation_time =", value, "reservationTime");
            return (Criteria) this;
        }

        public Criteria andReservationTimeNotEqualTo(Date value) {
            addCriterion("reservation_time <>", value, "reservationTime");
            return (Criteria) this;
        }

        public Criteria andReservationTimeGreaterThan(Date value) {
            addCriterion("reservation_time >", value, "reservationTime");
            return (Criteria) this;
        }

        public Criteria andReservationTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("reservation_time >=", value, "reservationTime");
            return (Criteria) this;
        }

        public Criteria andReservationTimeLessThan(Date value) {
            addCriterion("reservation_time <", value, "reservationTime");
            return (Criteria) this;
        }

        public Criteria andReservationTimeLessThanOrEqualTo(Date value) {
            addCriterion("reservation_time <=", value, "reservationTime");
            return (Criteria) this;
        }

        public Criteria andReservationTimeIn(List<Date> values) {
            addCriterion("reservation_time in", values, "reservationTime");
            return (Criteria) this;
        }

        public Criteria andReservationTimeNotIn(List<Date> values) {
            addCriterion("reservation_time not in", values, "reservationTime");
            return (Criteria) this;
        }

        public Criteria andReservationTimeBetween(Date value1, Date value2) {
            addCriterion("reservation_time between", value1, value2, "reservationTime");
            return (Criteria) this;
        }

        public Criteria andReservationTimeNotBetween(Date value1, Date value2) {
            addCriterion("reservation_time not between", value1, value2, "reservationTime");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("status like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("status not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andEntryQrCodeIsNull() {
            addCriterion("entry_qr_code is null");
            return (Criteria) this;
        }

        public Criteria andEntryQrCodeIsNotNull() {
            addCriterion("entry_qr_code is not null");
            return (Criteria) this;
        }

        public Criteria andEntryQrCodeEqualTo(String value) {
            addCriterion("entry_qr_code =", value, "entryQrCode");
            return (Criteria) this;
        }

        public Criteria andEntryQrCodeNotEqualTo(String value) {
            addCriterion("entry_qr_code <>", value, "entryQrCode");
            return (Criteria) this;
        }

        public Criteria andEntryQrCodeGreaterThan(String value) {
            addCriterion("entry_qr_code >", value, "entryQrCode");
            return (Criteria) this;
        }

        public Criteria andEntryQrCodeGreaterThanOrEqualTo(String value) {
            addCriterion("entry_qr_code >=", value, "entryQrCode");
            return (Criteria) this;
        }

        public Criteria andEntryQrCodeLessThan(String value) {
            addCriterion("entry_qr_code <", value, "entryQrCode");
            return (Criteria) this;
        }

        public Criteria andEntryQrCodeLessThanOrEqualTo(String value) {
            addCriterion("entry_qr_code <=", value, "entryQrCode");
            return (Criteria) this;
        }

        public Criteria andEntryQrCodeLike(String value) {
            addCriterion("entry_qr_code like", value, "entryQrCode");
            return (Criteria) this;
        }

        public Criteria andEntryQrCodeNotLike(String value) {
            addCriterion("entry_qr_code not like", value, "entryQrCode");
            return (Criteria) this;
        }

        public Criteria andEntryQrCodeIn(List<String> values) {
            addCriterion("entry_qr_code in", values, "entryQrCode");
            return (Criteria) this;
        }

        public Criteria andEntryQrCodeNotIn(List<String> values) {
            addCriterion("entry_qr_code not in", values, "entryQrCode");
            return (Criteria) this;
        }

        public Criteria andEntryQrCodeBetween(String value1, String value2) {
            addCriterion("entry_qr_code between", value1, value2, "entryQrCode");
            return (Criteria) this;
        }

        public Criteria andEntryQrCodeNotBetween(String value1, String value2) {
            addCriterion("entry_qr_code not between", value1, value2, "entryQrCode");
            return (Criteria) this;
        }

        public Criteria andExitQrCodeIsNull() {
            addCriterion("exit_qr_code is null");
            return (Criteria) this;
        }

        public Criteria andExitQrCodeIsNotNull() {
            addCriterion("exit_qr_code is not null");
            return (Criteria) this;
        }

        public Criteria andExitQrCodeEqualTo(String value) {
            addCriterion("exit_qr_code =", value, "exitQrCode");
            return (Criteria) this;
        }

        public Criteria andExitQrCodeNotEqualTo(String value) {
            addCriterion("exit_qr_code <>", value, "exitQrCode");
            return (Criteria) this;
        }

        public Criteria andExitQrCodeGreaterThan(String value) {
            addCriterion("exit_qr_code >", value, "exitQrCode");
            return (Criteria) this;
        }

        public Criteria andExitQrCodeGreaterThanOrEqualTo(String value) {
            addCriterion("exit_qr_code >=", value, "exitQrCode");
            return (Criteria) this;
        }

        public Criteria andExitQrCodeLessThan(String value) {
            addCriterion("exit_qr_code <", value, "exitQrCode");
            return (Criteria) this;
        }

        public Criteria andExitQrCodeLessThanOrEqualTo(String value) {
            addCriterion("exit_qr_code <=", value, "exitQrCode");
            return (Criteria) this;
        }

        public Criteria andExitQrCodeLike(String value) {
            addCriterion("exit_qr_code like", value, "exitQrCode");
            return (Criteria) this;
        }

        public Criteria andExitQrCodeNotLike(String value) {
            addCriterion("exit_qr_code not like", value, "exitQrCode");
            return (Criteria) this;
        }

        public Criteria andExitQrCodeIn(List<String> values) {
            addCriterion("exit_qr_code in", values, "exitQrCode");
            return (Criteria) this;
        }

        public Criteria andExitQrCodeNotIn(List<String> values) {
            addCriterion("exit_qr_code not in", values, "exitQrCode");
            return (Criteria) this;
        }

        public Criteria andExitQrCodeBetween(String value1, String value2) {
            addCriterion("exit_qr_code between", value1, value2, "exitQrCode");
            return (Criteria) this;
        }

        public Criteria andExitQrCodeNotBetween(String value1, String value2) {
            addCriterion("exit_qr_code not between", value1, value2, "exitQrCode");
            return (Criteria) this;
        }

        public Criteria andQrExpiryTimeIsNull() {
            addCriterion("qr_expiry_time is null");
            return (Criteria) this;
        }

        public Criteria andQrExpiryTimeIsNotNull() {
            addCriterion("qr_expiry_time is not null");
            return (Criteria) this;
        }

        public Criteria andQrExpiryTimeEqualTo(Date value) {
            addCriterion("qr_expiry_time =", value, "qrExpiryTime");
            return (Criteria) this;
        }

        public Criteria andQrExpiryTimeNotEqualTo(Date value) {
            addCriterion("qr_expiry_time <>", value, "qrExpiryTime");
            return (Criteria) this;
        }

        public Criteria andQrExpiryTimeGreaterThan(Date value) {
            addCriterion("qr_expiry_time >", value, "qrExpiryTime");
            return (Criteria) this;
        }

        public Criteria andQrExpiryTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("qr_expiry_time >=", value, "qrExpiryTime");
            return (Criteria) this;
        }

        public Criteria andQrExpiryTimeLessThan(Date value) {
            addCriterion("qr_expiry_time <", value, "qrExpiryTime");
            return (Criteria) this;
        }

        public Criteria andQrExpiryTimeLessThanOrEqualTo(Date value) {
            addCriterion("qr_expiry_time <=", value, "qrExpiryTime");
            return (Criteria) this;
        }

        public Criteria andQrExpiryTimeIn(List<Date> values) {
            addCriterion("qr_expiry_time in", values, "qrExpiryTime");
            return (Criteria) this;
        }

        public Criteria andQrExpiryTimeNotIn(List<Date> values) {
            addCriterion("qr_expiry_time not in", values, "qrExpiryTime");
            return (Criteria) this;
        }

        public Criteria andQrExpiryTimeBetween(Date value1, Date value2) {
            addCriterion("qr_expiry_time between", value1, value2, "qrExpiryTime");
            return (Criteria) this;
        }

        public Criteria andQrExpiryTimeNotBetween(Date value1, Date value2) {
            addCriterion("qr_expiry_time not between", value1, value2, "qrExpiryTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table reservations
     *
     * @mbg.generated do_not_delete_during_merge Wed Mar 26 00:44:02 CST 2025
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table reservations
     *
     * @mbg.generated Wed Mar 26 00:44:02 CST 2025
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}