package com.liu.gymmanagement.model;

import java.util.Date;

public class Reservation {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reservations.ReservationID
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    private Integer reservationid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reservations.UserID
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    private String userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reservations.GymID
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    private Integer gymid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reservations.StartTime
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    private Date starttime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reservations.EndTime
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    private Date endtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reservations.ReservationID
     *
     * @return the value of reservations.ReservationID
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    public Integer getReservationid() {
        return reservationid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reservations.ReservationID
     *
     * @param reservationid the value for reservations.ReservationID
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    public void setReservationid(Integer reservationid) {
        this.reservationid = reservationid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reservations.UserID
     *
     * @return the value of reservations.UserID
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reservations.UserID
     *
     * @param userid the value for reservations.UserID
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reservations.GymID
     *
     * @return the value of reservations.GymID
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    public Integer getGymid() {
        return gymid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reservations.GymID
     *
     * @param gymid the value for reservations.GymID
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    public void setGymid(Integer gymid) {
        this.gymid = gymid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reservations.StartTime
     *
     * @return the value of reservations.StartTime
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    public Date getStarttime() {
        return starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reservations.StartTime
     *
     * @param starttime the value for reservations.StartTime
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    public void setStarttime(Date starttime) {
        this.starttime = starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reservations.EndTime
     *
     * @return the value of reservations.EndTime
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    public Date getEndtime() {
        return endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reservations.EndTime
     *
     * @param endtime the value for reservations.EndTime
     *
     * @mbg.generated Thu Mar 20 02:19:12 CST 2025
     */
    public void setEndtime(Date endtime) {
        this.endtime = endtime;
    }
}