package com.liu.gymmanagement.model;

import java.time.LocalDateTime;
import java.util.Date;

public class Reservation {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reservations.ReservationID
     *
     * @mbg.generated Wed Mar 26 00:44:02 CST 2025
     */
    private Integer reservationid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reservations.UserID
     *
     * @mbg.generated Wed Mar 26 00:44:02 CST 2025
     */
    private String userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reservations.GymID
     *
     * @mbg.generated Wed Mar 26 00:44:02 CST 2025
     */
    private Integer gymid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reservations.TimeslotID
     *
     * @mbg.generated Wed Mar 26 00:44:02 CST 2025
     */
    private Integer timeslotid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reservations.reservation_time
     *
     * @mbg.generated Wed Mar 26 00:44:02 CST 2025
     */
    private LocalDateTime reservationTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reservations.status
     *
     * @mbg.generated Wed Mar 26 00:44:02 CST 2025
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reservations.entry_qr_code
     *
     * @mbg.generated Wed Mar 26 00:44:02 CST 2025
     */
    private String entryQrCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reservations.exit_qr_code
     *
     * @mbg.generated Wed Mar 26 00:44:02 CST 2025
     */
    private String exitQrCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reservations.qr_expiry_time
     *
     * @mbg.generated Wed Mar 26 00:44:02 CST 2025
     */
    private LocalDateTime qrExpiryTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reservations.ReservationID
     *
     * @return the value of reservations.ReservationID
     *
     * @mbg.generated Wed Mar 26 00:44:02 CST 2025
     */
    public Integer getReservationid() {
        return reservationid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reservations.ReservationID
     *
     * @param reservationid the value for reservations.ReservationID
     *
     * @mbg.generated Wed Mar 26 00:44:02 CST 2025
     */
    public void setReservationid(Integer reservationid) {
        this.reservationid = reservationid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reservations.UserID
     *
     * @return the value of reservations.UserID
     *
     * @mbg.generated Wed Mar 26 00:44:02 CST 2025
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reservations.UserID
     *
     * @param userid the value for reservations.UserID
     *
     * @mbg.generated Wed Mar 26 00:44:02 CST 2025
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reservations.GymID
     *
     * @return the value of reservations.GymID
     *
     * @mbg.generated Wed Mar 26 00:44:02 CST 2025
     */
    public Integer getGymid() {
        return gymid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reservations.GymID
     *
     * @param gymid the value for reservations.GymID
     *
     * @mbg.generated Wed Mar 26 00:44:02 CST 2025
     */
    public void setGymid(Integer gymid) {
        this.gymid = gymid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reservations.TimeslotID
     *
     * @return the value of reservations.TimeslotID
     *
     * @mbg.generated Wed Mar 26 00:44:02 CST 2025
     */
    public Integer getTimeslotid() {
        return timeslotid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reservations.TimeslotID
     *
     * @param timeslotid the value for reservations.TimeslotID
     *
     * @mbg.generated Wed Mar 26 00:44:02 CST 2025
     */
    public void setTimeslotid(Integer timeslotid) {
        this.timeslotid = timeslotid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reservations.reservation_time
     *
     * @return the value of reservations.reservation_time
     *
     * @mbg.generated Wed Mar 26 00:44:02 CST 2025
     */
    public LocalDateTime getReservationTime() {
        return reservationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reservations.reservation_time
     *
     * @param reservationTime the value for reservations.reservation_time
     *
     * @mbg.generated Wed Mar 26 00:44:02 CST 2025
     */
    public void setReservationTime(LocalDateTime reservationTime) {
        this.reservationTime = reservationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reservations.status
     *
     * @return the value of reservations.status
     *
     * @mbg.generated Wed Mar 26 00:44:02 CST 2025
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reservations.status
     *
     * @param status the value for reservations.status
     *
     * @mbg.generated Wed Mar 26 00:44:02 CST 2025
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reservations.entry_qr_code
     *
     * @return the value of reservations.entry_qr_code
     *
     * @mbg.generated Wed Mar 26 00:44:02 CST 2025
     */
    public String getEntryQrCode() {
        return entryQrCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reservations.entry_qr_code
     *
     * @param entryQrCode the value for reservations.entry_qr_code
     *
     * @mbg.generated Wed Mar 26 00:44:02 CST 2025
     */
    public void setEntryQrCode(String entryQrCode) {
        this.entryQrCode = entryQrCode == null ? null : entryQrCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reservations.exit_qr_code
     *
     * @return the value of reservations.exit_qr_code
     *
     * @mbg.generated Wed Mar 26 00:44:02 CST 2025
     */
    public String getExitQrCode() {
        return exitQrCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reservations.exit_qr_code
     *
     * @param exitQrCode the value for reservations.exit_qr_code
     *
     * @mbg.generated Wed Mar 26 00:44:02 CST 2025
     */
    public void setExitQrCode(String exitQrCode) {
        this.exitQrCode = exitQrCode == null ? null : exitQrCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reservations.qr_expiry_time
     *
     * @return the value of reservations.qr_expiry_time
     *
     * @mbg.generated Wed Mar 26 00:44:02 CST 2025
     */
    public LocalDateTime getQrExpiryTime() {
        return qrExpiryTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reservations.qr_expiry_time
     *
     * @param qrExpiryTime the value for reservations.qr_expiry_time
     *
     * @mbg.generated Wed Mar 26 00:44:02 CST 2025
     */
    public void setQrExpiryTime(LocalDateTime qrExpiryTime) {
        this.qrExpiryTime = qrExpiryTime;
    }
}