package com.liu.gymmanagement.model;

import java.time.LocalDate;
import java.util.Date;

public class WorkoutLog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workout_log.WorkoutLogID
     *
     * @mbg.generated Sun Apr 13 21:46:58 CST 2025
     */
    private Integer workoutlogid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workout_log.UserID
     *
     * @mbg.generated Sun Apr 13 21:46:58 CST 2025
     */
    private String userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workout_log.Date
     *
     * @mbg.generated Sun Apr 13 21:46:58 CST 2025
     */
    private LocalDate date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workout_log.DurationMinutes
     *
     * @mbg.generated Sun Apr 13 21:46:58 CST 2025
     */
    private Integer durationminutes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workout_log.ActivityType
     *
     * @mbg.generated Sun Apr 13 21:46:58 CST 2025
     */
    private String activitytype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workout_log.Notes
     *
     * @mbg.generated Sun Apr 13 21:46:58 CST 2025
     */
    private String notes;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column workout_log.WorkoutLogID
     *
     * @return the value of workout_log.WorkoutLogID
     *
     * @mbg.generated Sun Apr 13 21:46:58 CST 2025
     */
    public Integer getWorkoutlogid() {
        return workoutlogid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column workout_log.WorkoutLogID
     *
     * @param workoutlogid the value for workout_log.WorkoutLogID
     *
     * @mbg.generated Sun Apr 13 21:46:58 CST 2025
     */
    public void setWorkoutlogid(Integer workoutlogid) {
        this.workoutlogid = workoutlogid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column workout_log.UserID
     *
     * @return the value of workout_log.UserID
     *
     * @mbg.generated Sun Apr 13 21:46:58 CST 2025
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column workout_log.UserID
     *
     * @param userid the value for workout_log.UserID
     *
     * @mbg.generated Sun Apr 13 21:46:58 CST 2025
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column workout_log.Date
     *
     * @return the value of workout_log.Date
     *
     * @mbg.generated Sun Apr 13 21:46:58 CST 2025
     */
    public LocalDate getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column workout_log.Date
     *
     * @param date the value for workout_log.Date
     *
     * @mbg.generated Sun Apr 13 21:46:58 CST 2025
     */
    public void setDate(LocalDate date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column workout_log.DurationMinutes
     *
     * @return the value of workout_log.DurationMinutes
     *
     * @mbg.generated Sun Apr 13 21:46:58 CST 2025
     */
    public Integer getDurationminutes() {
        return durationminutes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column workout_log.DurationMinutes
     *
     * @param durationminutes the value for workout_log.DurationMinutes
     *
     * @mbg.generated Sun Apr 13 21:46:58 CST 2025
     */
    public void setDurationminutes(Integer durationminutes) {
        this.durationminutes = durationminutes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column workout_log.ActivityType
     *
     * @return the value of workout_log.ActivityType
     *
     * @mbg.generated Sun Apr 13 21:46:58 CST 2025
     */
    public String getActivitytype() {
        return activitytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column workout_log.ActivityType
     *
     * @param activitytype the value for workout_log.ActivityType
     *
     * @mbg.generated Sun Apr 13 21:46:58 CST 2025
     */
    public void setActivitytype(String activitytype) {
        this.activitytype = activitytype == null ? null : activitytype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column workout_log.Notes
     *
     * @return the value of workout_log.Notes
     *
     * @mbg.generated Sun Apr 13 21:46:58 CST 2025
     */
    public String getNotes() {
        return notes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column workout_log.Notes
     *
     * @param notes the value for workout_log.Notes
     *
     * @mbg.generated Sun Apr 13 21:46:58 CST 2025
     */
    public void setNotes(String notes) {
        this.notes = notes == null ? null : notes.trim();
    }
}